### PR TITLE
added self-employed conditional logic to jobs[i].complete block

### LINKED ISSUE #85: self employed job
When we are gathering job info, if they select I am self-employed, they are supposed to jump to a screen that collects their self-employment income rather than their wages. (It's reported on a different line on the form.) 

image

It should jump someone to this screen   id: id: self employed income

Not sure how we want to handle that now with all the recent changes.

Do we have to ask up-front if they have self-employment income before we gather jobs???

### PR DESCRIPTION
**Pull request by tobyfey**
fix #85 

Changed the jobs[i].complete block to ask self employment questions if needed.

### CODE REVIEW

**Comment by VTskier** [comment]
@tobyfey It's awkward when you say you have a job and it's self-employed and then you see the job review screen and the regular review screen. And then you try to edit your self-employed job. and you get the regular job wages question. Any suggestions?

image

image

As I mentioned, the self-employed income will always have its own line item on the forms.

**Comment by tobyfey** [comment]
I'll work on the bug with the edit button, but do you want two separate tables and buttons on the review screen?  It seems like we should do the same with the Review your jobs screen.

**Comment by VTskier** [comment]
"do you want two separate tables and buttons on the review screen? It seems like we should do the same with the Review your jobs screen"

I guess? Not sure what that will look and feel like.

**Comment by tobyfey** [comment]
I tried making two tables first on the Review your jobs signs, and I put it into the review screen, forgetting the review screen doesn't use tables.  But it could be an easier interface -

image

I could switch that to look like the rest of the review screen.  Or do we want to use tables more throughout the review screen.

Here is the Review your jobs screen

image

There's only one add job, which will then let somebody pick self-employed or not.  If that's okay, that will be easier to do (and it will be easier to do on the review screen).


If that looks okay, then I still have some cleaning up.

**Comment by VTskier** [comment]
Thanks, I'm checking it out. I'm trying to keep the overall Review screen pretty neat and simple.

**Comment by VTskier** [comment]
I like the job review screen (id: job review). 

The regular review screen has too much. Could it be just the job name and then the edit and delete buttons next to each job? I'm assuming it helps with the coding to have the edit and delete buttons right there in view of the user.

image

**Comment by tobyfey** [comment]
How about this for the review screen?

image

**Comment by VTskier** [comment]
@tobyfey Let's try it and see what testers think. Thank you!

**Comment by tobyfey** [comment]
Ok, I am going to do a test with no jobs and I'll commit if it works.

**Comment by VTskier** [comment]
@tobyfey The review stuff looks good!

I think maybe you changed a variable or something for self-employed income, so now it isn't showing up on the PDF. This should have self-employed income.

image

**Comment by tobyfey** [comment]
I should have mentioned that and meant to ask - I did change the variable `users1_income_self_employment_monthly_amount` to instead be an attribute of a job - `jobs[i].income_self_employment_monthly_amount`

I thought could have more than one self-employed job, so I thought that was necessary.

Should that field be a total of all the self-employed jobs?  (We may want to set `jobs[i].value` to `jobs[i].income_self_employment_monthly_amount` so we can use the total method.

**Comment by VTskier** [comment]
@tobyfey Yes, should be a total of all self-employed jobs. Then gets included in total monthly and annual income.

**Comment by VTskier** [comment]
_Should that field be a total of all the self-employed jobs? (We may want to set jobs[i].value to jobs[i].income_self_employment_monthly_amount so we can use the total method._

@tobyfey Are you able to start those changes? I'm not sure what to change.

**Comment by tobyfey** [comment]
Yes, I'm working on this.  I think the best way to do it may be to make "self employed" a "source" like "part time" or "full time".

**Comment by VTskier** [comment]
@tobyfey I entered one regular job and one self-employed. The SE figures and income totals did not appear on the PDF.

In attachment code, I removed the floats from 
"users1_income_self_employment_monthly_amount"
"users1_income_monthly_total"
"users1_income_annual_total"
The figures then appeared on the PDF.

I used the Review Screen to Add another job. I added another regular and another SE job. They showed up on the review screen.
The SE figures and income totals did not appear on the PDF.

Also, I'm not able to use the Edit buttons for the SE jobs on the review screen.

**Comment by tobyfey** [comment]
This seems like an issue with .times_per_year being added to the self-employed income.  I can work on this after a meeting this morning.

**Comment by VTskier** [comment]
@tobyfey Great! Totals are working. Now just need to be able to edit the self-employed jobs using the Edit buttons on the Review Screen. When I click them, it just reloads the page.

Thank you!

**Comment by tobyfey** [comment]
I think the pdf is working better but the review tables aren't working right - edit isn't working in the self-employed jobs, and delete deletes the wrong thing (seems to delete jobs[0] when you delete the first item in the self-employment table, even  if that's a job with the employer)

**Comment by VTskier** [comment]
Oh, yeah. Now I see the delete problem.

**Comment by tobyfey** [comment]
This is also happening in the review screen immediately after the question.  I don't know if there is going to be a good way to fix this using two tables.  The easiest thing to do would be to have one table for all jobs, including self employed (we could have separate totals for employer jobs and self employed on the review screen with the table).

**Pull request merged**
